.PHONY: clean


pointerlist:
	@chmod 755 .
	@python pointerlist.py

	@chmod 755 .
	@python arraylist.py


	@chmod 755 .
	@python pointerstack.py


	@chmod 755 .
	@python arraystack.py

clean:
	@\rm -f *.pyc