all : pointerqueue lcrstree levelorder traversalconvert preorder postorder listconcat
.PHONY : all

pointerqueue:
	python pointerqueue.py

lcrstree:
	python lcrstree.py

levelorder:
	python levelorder.py

traversalconvert:
	python traversalconvert.py

preorder:
	python preorder.py

postorder:
	python postorder.py

listconcat:
	python listconcat.py

